services:
  ascolour:
    container_name: "ascolour"
    platform: linux/x86_64
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - .:/app
      - ascolour_bundle:/usr/local/bundle
    working_dir: /app
    # Keeps the stdin open, so we can attach to our app container's process and
    # do stuff such as `byebug` or `binding.pry`:
    stdin_open: true
    # Allows us to send signals (CTRL+C, CTRL+P + CTRL+Q) into the container
    tty: true

volumes:
  ascolour_bundle:
